export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const REDIRECT = "REDIRECT";
export const GOOGLE_USER = "GOOGLE_USER";
export const UPDATE_FAIL = "UPDATE_FAIL";
export const GET_CURRENT_AUTH_STATUS_SUCCESS =
  "GET_CURRENT_AUTH_STATUS_SUCCESS";
export const GET_CURRENT_AUTH_STATUS_FAIL = "GET_CURRENT_AUTH_STATUS_FAIL";
export const SET_CSRF_TOKEN = "SET_CSRF_TOKEN";

export const ASYNC_START = "ASYNC_START";
export const GET_CURRENT_PROFILE_SUCCESS = "GET_CURRENT_PROFILE_SUCCESS";
export const GET_CURRENT_PROFILE_FAIL = "GET_CURRENT_PROFILE_FAIL";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const CREATE_PROFILE_FAIL = "CREATE_PROFILE_FAIL";
export const ADD_EDUCATION_FAIL = "ADD_EDUCATION_FAIL";
export const ADD_EXPERIENCE_FAIL = "ADD_EXPERIENCE_FAIL";
export const GET_PROFILES_SUCCESS = "GET_PROFILES_SUCCESS";
export const GET_PROFILES_FAIL = "GET_PROFILES_FAIL";
export const GET_OTHER_PROFILE_SUCCESS = "GET_OTHER_PROFILE_SUCCESS";
export const CLEAR_OTHER_PROFILE = "CLEAR_OTHER_PROFILE";

///////////////////
export const FETCH_ARTICLES_START = "FETCH_ARTICLES_START";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_FAIL = "FETCH_ARTICLES_FAIL";
export const FETCH_MY_ARTICLES_SUCCESS = "FETCH_MY_ARTICLES_SUCCESS";
export const SET_FEED = "SET_FEED";
export const SET_ALL = "SET_ALL";
export const SET_TAG = "SET_TAG";
export const CLEAR_TAG = "CLEAR_TAG";

export const SET_PAGE = "SET_PAGE";

export const FETCH_TAGS_START = "FETCH_TAGS_START";
export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";
export const FETCH_TAGS_FAIL = "FETCH_TAGS_FAIL";
//////////////////////
export const CHECK_SUCCESS = "CHECK_SUCCESS";

export const SETTINGS_START = "SETTINGS_START";
export const SETTINGS_SUCCESS = "SETTINGS_SUCCESS";
export const SETTINGS_FAIL = "SETTINGS_FAIL";

export const FETCH_ARTICLE_START = "FETCH_ARTICLE_START";
export const FETCH_ARTICLE_SUCCESS = "FETCH_ARTICLE_SUCCESS";
export const FETCH_ARTICLE_FAIL = "FETCH_ARTICLE_FAIL";
export const FETCH_SINGLEARTICLE_SUCCESS = "FETCH_SINGLEARTICLE_SUCCESS";
export const FAV_SINGLEARTICLE_SUCCESS = "FAV_SINGLEARTICLE_SUCCESS";

export const ADD_ARTICLE_START = "ADD_ARTICLE_START";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_FAIL = "ADD_ARTICLE_FAIL";

export const UPDATE_ARTICLE_START = "UPDATE_ARTICLE_START";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAIL = "UPDATE_ARTICLE_FAIL";

export const DELETE_ARTICLE_START = "DELETE_ARTICLE_START";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_FAIL = "DELETE_ARTICLE_FAIL";

export const FETCH_COMMENTS_START = "FETCH_COMMENTS_START";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAIL = "FETCH_COMMENTS_FAIL";

export const DELETE_COMMENT_START = "DELETE_COMMENT_START";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

export const ADD_COMMENT_START = "ADD_COMMENT_START";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const FETCH_PROFILE_START = "FETCH_PROFILE_START";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL";

export const FOLLOW_PROFILE_START = "FOLLOW_PROFILE_START";
export const FOLLOW_PROFILE_SUCCESS = "FOLLOW_PROFILE_SUCCESS";
export const FOLLOW_PROFILE_FAIL = "FOLLOW_PROFILE_FAIL";

export const UNFOLLOW_PROFILE_START = "UNFOLLOW_PROFILE_START";
export const UNFOLLOW_PROFILE_SUCCESS = "UNFOLLOW_PROFILE_SUCCESS";
export const UNFOLLOW_PROFILE_FAIL = "UNFOLLOW_PROFILE_FAIL";

export const ARTICLE_PAGE_UNLOADED = "ARTICLE_PAGE_UNLOADED";
export const PROFILE_PAGE_UNLOADED = "PROFILE_PAGE_UNLOADED";
export const PROFILE_FAVORITES_PAGE_UNLOADED =
  "PROFILE_FAVORITES_PAGE_UNLOADED";

export const CREATE_PAGE_LOADED = "CREATE_PAGE_LOADED";
export const EDITOR_PAGE_UNLOADED = "EDITOR_PAGE_UNLOADED";
export const ADD_TAG = "ADD_TAG";
export const REMOVE_TAG = "REMOVE_TAG";
export const UPDATE_FIELD_EDITOR = "UPDATE_FIELD_EDITOR";

export const FETCH_EVENTS_START = "FETCH_EVENTS_START";
export const FETCH_EVENTS_FAIL = "FETCH_EVENTS_FAIL";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";

export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";

export const MSG_LIST = "MSG_LIST";
export const MSG_RECV_SUCCESS = "MSG_RECV_SUCCESS";
export const MSG_READ = "MSG_READ";
export const OPEN_BOX = "OPEN_BOX";
export const OPEN_LIST = "OPEN_LIST";
export const TOGGLE_BOX = "TOGGLE_BOX";

export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
